import { FileUpload as BaseFileUpload } from "@ark-ui/react";
import { ComponentMetadata, ComposedTVProps } from "react-tvcx";
export declare const fileUpload: import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>;
export interface FileUploadProps extends ComposedTVProps<typeof fileUpload> {
}
export interface FileUpload extends ComponentMetadata {
    (props: FileUploadProps): React.ReactElement | null;
}
export declare const FileUpload: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.RootProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & object & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>> & {
    Root: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.RootProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & object & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    RootProvider: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.RootProviderProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & object & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    Context: import("react").ForwardRefExoticComponent<BaseFileUpload.ContextProps & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<never>>;
    Dropzone: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.DropzoneProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    HiddenInput: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.HiddenInputProps & import("react").RefAttributes<HTMLInputElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLInputElement>>;
    Item: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemProps & import("react").RefAttributes<HTMLLIElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLLIElement>>;
    ItemDeleteTrigger: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemDeleteTriggerProps & import("react").RefAttributes<HTMLButtonElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLButtonElement>>;
    ItemGroup: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemGroupProps & import("react").RefAttributes<HTMLUListElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLUListElement>>;
    ItemName: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemNameProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    ItemPreview: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemPreviewProps & import("react").RefAttributes<HTMLImageElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLImageElement>>;
    ItemPreviewImage: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemPreviewImageProps & import("react").RefAttributes<HTMLImageElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLImageElement>>;
    ItemSizeText: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemSizeTextProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    Label: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.LabelProps & import("react").RefAttributes<HTMLLabelElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLLabelElement>>;
    Trigger: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.TriggerProps & import("react").RefAttributes<HTMLButtonElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLButtonElement>>;
} & Readonly<{
    Root: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.RootProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & object & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    RootProvider: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.RootProviderProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & object & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    Context: import("react").ForwardRefExoticComponent<BaseFileUpload.ContextProps & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<never>>;
    Dropzone: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.DropzoneProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    HiddenInput: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.HiddenInputProps & import("react").RefAttributes<HTMLInputElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLInputElement>>;
    Item: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemProps & import("react").RefAttributes<HTMLLIElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLLIElement>>;
    ItemDeleteTrigger: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemDeleteTriggerProps & import("react").RefAttributes<HTMLButtonElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLButtonElement>>;
    ItemGroup: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemGroupProps & import("react").RefAttributes<HTMLUListElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLUListElement>>;
    ItemName: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemNameProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    ItemPreview: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemPreviewProps & import("react").RefAttributes<HTMLImageElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLImageElement>>;
    ItemPreviewImage: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemPreviewImageProps & import("react").RefAttributes<HTMLImageElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLImageElement>>;
    ItemSizeText: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.ItemSizeTextProps & import("react").RefAttributes<HTMLDivElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLDivElement>>;
    Label: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.LabelProps & import("react").RefAttributes<HTMLLabelElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLLabelElement>>;
    Trigger: import("react").ForwardRefExoticComponent<Omit<BaseFileUpload.TriggerProps & import("react").RefAttributes<HTMLButtonElement>, "ref"> & import("tailwind-variants").VariantProps<import("tailwind-variants").TVReturnType<{} | {} | {}, undefined, "", {} | {}, undefined, import("tailwind-variants").TVReturnType<unknown, undefined, "", unknown, unknown, undefined>>> & import("react-tvcx").UnstyledProps & import("react").RefAttributes<HTMLButtonElement>>;
}>;
//# sourceMappingURL=file-upload.d.ts.map